#!/usr/bin/env bash

## the first arg is the path to the git commit temporary file
TEMPORARY_FILE_PATH=$1

## get commit-message from the temporary file
COMMIT_MSG=`head -n1 $TEMPORARY_FILE_PATH`

## init regex to match commit-message format
COMMIT_MSG_REGEX="\#[0-9]+|Merge branch\s.*"

## checking commit-message format
if ! [[ $COMMIT_MSG =~ $COMMIT_MSG_REGEX ]]; then
    echo -e "Your commit-message format is not valid:\n$COMMIT_MSG\n"
    echo "Valid format example:"
    echo "#issueNumber My commit message"
    exit 1
else
    exit 0
fi