version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: swagger
    environment:
      - SWAGGER_JSON=/openapi/api.yaml
    ports:
      - "8083:8080"
    volumes:
      - ./v1:/openapi
    restart: always
