export const MAX_LOCAL_CACHE_SIZE_COUNT = 1000
export const MAX_GEOHASH_CACHE_ENTRIES_COUNT = 1000
export const MAX_GEOHASH_CACHE_MB_SIZE = 20
export const MAX_GEOHASH_CACHE_CACHE_TIMEOUT_MINUTES = 20
