export const MAX_LOCAL_CACHE_SIZE_COUNT = 1000
export const MAX_GEOHASH_CACHE_ENTRIES_COUNT = 1000
export const MAX_GEOHASH_CACHE_MB_SIZE = 20
export const MAX_GEOHASH_CACHE_TIMEOUT_MINUTES = 20
export const MAX_GEOHASH_NEIGHBOR_SEARCH_LEVEL = 20
export const CACHE_GEOHASH_PREFIX_LENGTH = 6
export const NEIGHBOR_SEARCH_GEOHASH_PREFIX_LENGTH = 7
export const MAX_GEOHASHES_PER_PROCESSING_BATCH = 32
