services:
  swagger-ui:
    build: .
    container_name: swagger-ui
    ports:
      - "8080:80"
    entrypoint: ["/bin/sh", "-c", "bin/sh /generate-token.sh"]
    environment:
      - LOCALSTACK_ENDPOINT=http://host.docker.internal:4566
    depends_on:
      - nginx

  nginx:
    build: .
    container_name: swagger-nginx
    ports:
      - "8081:80"
    entrypoint: ["/bin/sh", "-c", "bin/sh /process-openapi.sh && nginx -g 'daemon off;'"]
    environment:
      - ENVIRONMENT=localstack
      - API_VERSION=v1
      - LOCALSTACK_ENDPOINT=http://host.docker.internal:4566
    restart: always
