name: "Save Deployment Metadata"
description: "Saves the current branch's commit info as JSON file and uploads it to S3."
inputs:
  environment_name:
    description: "Deployment Environment name"
    required: true
  role_arn:
    description: "AWS Role ARN to assume"
    required: true
  aws_region:
    description: "AWS Region"
    required: true
  bucket_name:
    description: "S3 Bucket name"
    required: true

runs:
  using: "composite"
  steps:
    - name: Save Deployment Metadata
      run: |
        LATEST_COMMIT_HASH=$(git rev-parse HEAD)
        echo "{\"last_deployed_commit\": \"$LATEST_COMMIT_HASH\"}" > deployment-info.json
      shell: bash

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ inputs.role_arn }}
        role-session-name: GitHubActions
        aws-region: ${{ inputs.aws_region }}

    - name: Upload Deployment Metadata to S3
      run: |
        aws s3 cp deployment-info.json s3://${{ inputs.bucket_name }}/deployment-info/${{ inputs.environment_name }}.json
      shell: bash
