export enum SCREENS {
  REGISTER = 'Register',
  LOGIN = 'Login',
  SET_PASSWORD = 'SetPassword',
  OTP = 'OTP',
  FORGOT_PASSWORD = 'ForgotPassword',
  PROFILE = 'Profile',
  WELCOME = 'Welcome',
  DONATION = 'Donation',
  DONATION_POSTS = 'DonationPosts',
  ADD_PERSONAL_INFO = 'AddPersonalInfo',
  BOTTOM_TABS = 'BottomTabs',
  HOME = 'Home',
  POSTS = 'Posts',
  MY_ACTIVITY = 'MyActivity',
}
