export enum SCREENS {
  REGISTER = 'Register',
  LOGIN = 'Login',
  SET_PASSWORD = 'SetPassword',
  OTP = 'OTP',
  FORGOT_PASSWORD = 'ForgotPassword',
  PROFILE = 'Profile',
  EDIT_PROFILE = 'EditProfile',
  WELCOME = 'Welcome',
  DONATION = 'Donation',
  DONATION_POSTS = 'DonationPosts',
  BOTTOM_TABS = 'BottomTabs',
  ACCOUNT = 'Account',
  ADD_PERSONAL_INFO = 'AddPersonalInfo',
  HOME = 'Home',
  POSTS = 'Posts',
  MY_ACTIVITY = 'My Activity',
  BLOOD_REQUEST_PREVIEW = 'BloodRequestPreview',
  DETAIL_POST = 'DetailPost',
  DONOR_PROFILE = 'DonorProfile',
  DONOR_RESPONSE = 'DonorResponse',
  REQUEST_STATUS = 'RequestStatus',
  DONOR_CONFIRMATION = 'DonorConfirmation',
  ABOUT = 'About'
}
