openapi: "3.1.0"

info:
  title: BloodConnect API Documentation
  version: "v1"
  description: This is the specification of parameters

paths: {}

components:
  parameters:
    test-id:
      name: test-id
      in: path
      required: true
      schema: { $ref: "schemas.yaml#/components/schemas/ID" }
      description: ID of a resource.
