openapi: "3.1.0"
info:
  title: BloodConnect API Documentation
  version: "v1"
  description: This is the specification of schemas

paths: {}

components:
  schemas:
    ID:
      title: Resource identifier
      description: |
        Unique identifier used for identification of individual resources
      type: string
      format: uuid
      example: 46106fd4-f16f-4f0f-a8a0-9c34e78b9ada

    Error:
      type: object
      properties:
        error: { $ref: "#/components/schemas/ErrorContent" }

    ErrorContent:
      type: object
      properties:
        code:
          type: string
        message:
          type: string

    RefreshTokenResponse:
      type: object
      required:
        - refresh-token
      properties:
        refresh-token: { $ref: "#/components/schemas/ID" }
      example: { $ref: "examples.yaml#/components/examples/RefreshToken" }
