openapi: "3.0.1"
tags:
  - name: bloodconnect
    description: API Endpoints for BloodConnect
  - name: bloodconnect-auth
    description: Auth module of BloodConnect

info:
  title: BloodConnect API <<ENVIRONMENT>>
  description: "BloodConnect API"
  version: "when_no_match"
  contact:
    name: Craftsmen Ltd.
    url: "https://craftsmenltd.com/"
  license:
    name: Apache 2.0
    url: "https://www.apache.org/licenses/LICENSE-2.0"

servers:
  - url: "http://<<API_GATEWAY_ID>>.execute-api.localhost.localstack.cloud:4566/<<ENVIRONMENT>>"
    description: localstack
  - url: "http://localhost:4566/<<API_VERSION>>"
    description: Local
  - url: "https://<<ENVIRONMENT>>.bloodconnect.net/<<API_VERSION>>"
    description: <<ENVIRONMENT>>

paths:
  /auth/refresh-token:
    $ref: "./../paths/auth/refresh-token.yml"

  /auth/register-organization:
    $ref: "./../paths/auth/register-organization.yml"

x-amazon-apigateway-request-validators:
  $ref: "./../validators.yml"
