export const genderOptions = [
  { label: 'Male', value: 'male' },
  { label: 'Female', value: 'female' },
  { label: 'Other', value: 'other' }
]

export const bloodGroupOptions = [
  { label: 'A+', value: 'A+' },
  { label: 'A-', value: 'A-' },
  { label: 'B+', value: 'B+' },
  { label: 'B-', value: 'B-' },
  { label: 'AB+', value: 'AB+' },
  { label: 'AB-', value: 'AB-' },
  { label: 'O+', value: 'O+' },
  { label: 'O-', value: 'O-' }
]

export const districts = [
  { label: 'Dhaka', value: 'Dhaka' },
  { label: 'Faridpur', value: 'Faridpur' },
  { label: 'Gazipur', value: 'Gazipur' },
  { label: 'Gopalganj', value: 'Gopalganj' },
  { label: 'Jamalpur', value: 'Jamalpur' },
  { label: 'Kishoreganj', value: 'Kishoreganj' },
  { label: 'Madaripur', value: 'Madaripur' },
  { label: 'Manikganj', value: 'Manikganj' },
  { label: 'Munshiganj', value: 'Munshiganj' },
  { label: 'Mymensingh', value: 'Mymensingh' },
  { label: 'Narayanganj', value: 'Narayanganj' },
  { label: 'Narsingdi', value: 'Narsingdi' },
  { label: 'Netrokona', value: 'Netrokona' },
  { label: 'Rajbari', value: 'Rajbari' },
  { label: 'Shariatpur', value: 'Shariatpur' },
  { label: 'Sherpur', value: 'Sherpur' },
  { label: 'Tangail', value: 'Tangail' },
  { label: 'Bogura', value: 'Bogura' },
  { label: 'Joypurhat', value: 'Joypurhat' },
  { label: 'Naogaon', value: 'Naogaon' },
  { label: 'Natore', value: 'Natore' },
  { label: 'Nawabganj', value: 'Nawabganj' },
  { label: 'Pabna', value: 'Pabna' },
  { label: 'Rajshahi', value: 'Rajshahi' },
  { label: 'Sirajgonj', value: 'Sirajgonj' },
  { label: 'Dinajpur', value: 'Dinajpur' },
  { label: 'Gaibandha', value: 'Gaibandha' },
  { label: 'Kurigram', value: 'Kurigram' },
  { label: 'Lalmonirhat', value: 'Lalmonirhat' },
  { label: 'Nilphamari', value: 'Nilphamari' },
  { label: 'Panchagarh', value: 'Panchagarh' },
  { label: 'Rangpur', value: 'Rangpur' },
  { label: 'Thakurgaon', value: 'Thakurgaon' },
  { label: 'Barguna', value: 'Barguna' },
  { label: 'Barishal', value: 'Barishal' },
  { label: 'Bhola', value: 'Bhola' },
  { label: 'Jhalokati', value: 'Jhalokati' },
  { label: 'Patuakhali', value: 'Patuakhali' },
  { label: 'Pirojpur', value: 'Pirojpur' },
  { label: 'Bandarban', value: 'Bandarban' },
  { label: 'Brahmanbaria', value: 'Brahmanbaria' },
  { label: 'Chandpur', value: 'Chandpur' },
  { label: 'Chattogram', value: 'Chattogram' },
  { label: 'Cumilla', value: 'Cumilla' },
  { label: "Cox's Bazar", value: "Cox's Bazar" },
  { label: 'Feni', value: 'Feni' },
  { label: 'Khagrachari', value: 'Khagrachari' },
  { label: 'Lakshmipur', value: 'Lakshmipur' },
  { label: 'Noakhali', value: 'Noakhali' },
  { label: 'Rangamati', value: 'Rangamati' },
  { label: 'Habiganj', value: 'Habiganj' },
  { label: 'Maulvibazar', value: 'Maulvibazar' },
  { label: 'Sunamganj', value: 'Sunamganj' },
  { label: 'Sylhet', value: 'Sylhet' },
  { label: 'Bagerhat', value: 'Bagerhat' },
  { label: 'Chuadanga', value: 'Chuadanga' },
  { label: 'Jashore', value: 'Jashore' },
  { label: 'Jhenaidah', value: 'Jhenaidah' },
  { label: 'Khulna', value: 'Khulna' },
  { label: 'Kushtia', value: 'Kushtia' },
  { label: 'Magura', value: 'Magura' },
  { label: 'Meherpur', value: 'Meherpur' },
  { label: 'Narail', value: 'Narail' },
  { label: 'Satkhira', value: 'Satkhira' }
]
