name: 📱 Mobile Preview Build

on:
  push:
    branches:
      - build-pipeline
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/app-build.yml
    with:
      build_type: preview
      mobile_branch: ${{ github.event.inputs.mobile_branch }}
      backend_branch: ${{ github.event.inputs.backend_branch }}