name: Aws Environment Terraform

on:
  workflow_call:
    inputs:
      github_environment:
        description: 'Defines the github environemnt for secrets'
        required: true
        type: string
      deployment_environment:
        description: 'Defines the deployment environemnt for makefile'
        required: true
        type: string
      tf_action:
        description: 'Terraform action to perform'
        required: true
        type: string
      tf_backend_bucket_name:
        description: 'Terraform backend bucket Name'
        required: true
        type: string
      tf_backend_bucket_key:
        description: 'Terraform backend bucket Key'
        required: true
        type: string
      tf_backend_bucket_region:
        description: 'Terraform backend bucket Region'
        required: true
        type: string
      aws_region:
        description: 'AWS region'
        required: true
        type: string
      tf_vars:
        description: 'Terraform Variables in YAML format'
        required: false
        type: string
        default: |

permissions:
  contents: read
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}

env:
  DOCKERFILE_PATH: ./Dockerfile
  CONTAINER_REGISTRY: ghcr.io
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  aws-terraform-env:
    environment: ${{ inputs.github_environment }}
    name: Aws Environment Terraform
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set Runner Image Name
        run: echo "RUNNER_IMAGE_NAME=${{ env.CONTAINER_REGISTRY }}/craftsmenltd/bloodconnect-ci-image:$(md5sum ${{ env.DOCKERFILE_PATH }} | awk '{ print $1 }')" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attempt to Pull Docker Image
        id: pull_docker_image
        run: docker pull ${{ env.RUNNER_IMAGE_NAME }}
        continue-on-error: true

      - name: Build Docker Image
        if: always() && steps.pull_docker_image.outcome == 'failure'
        run: make build-runner-image
        id: build_docker_image

      - name: Push Docker Image
        if: always() && steps.build_docker_image.outcome == 'failure'
        run: docker push ${{ env.RUNNER_IMAGE_NAME }}

      - name: Install Node Modules
        run: make run-command-install-node-packages

      - name: Package Code
        run: make run-command-package-all

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ inputs.aws_region }}

      - name: Set Environment Variables for Deployment
        run: |
          echo "DEPLOYMENT_ENVIRONMENT=${{ inputs.deployment_environment }}" >> $GITHUB_ENV
          echo "TF_BACKEND_BUCKET_NAME=${{ inputs.tf_backend_bucket_name }}" >> $GITHUB_ENV
          echo "TF_BACKEND_BUCKET_KEY=${{ inputs.tf_backend_bucket_key }}" >> $GITHUB_ENV
          echo "TF_BACKEND_BUCKET_REGION=${{ inputs.tf_backend_bucket_region }}" >> $GITHUB_ENV
          echo "AWS_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV
          echo "AWS_DEFAULT_REGION=${{ inputs.aws_region }}" >> $GITHUB_ENV

      - name: Parse and Set Terraform Variables
        run: echo "${{ inputs.tf_vars }}" | xargs -d '\n' -I {} echo {} >> $GITHUB_ENV

      - name: Terraform Initialization
        run: make run-command-tf-init

      - name: Terraform Plan ${{ inputs.tf_action }}
        run: make run-command-tf-plan-${{ inputs.tf_action }}

      - name: Terraform ${{ inputs.tf_action }}
        run: make run-command-tf-${{ inputs.tf_action }}
