name: Build React Native App with Expo

on:
  push:
    branches:
      - build-pipeline
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install AWS CLI
        run: |
          sudo apt update
          sudo apt install -y awscli

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
        

      - name: Fetch Cognito Details
        run: |
          # Fetch specific Cognito User Pool ID
          USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 20 | jq -r '.UserPools[] | select(.Name=="stage-user-pool") | .Id')
      
          # Fetch specific Cognito Client ID
          CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id $USER_POOL_ID --max-results 20 | jq -r '.UserPoolClients[] | select(.ClientName=="stage-user-pool-client") | .ClientId')
      
          # Fetch specific API Gateway ID
          API_ID=$(aws apigateway get-rest-apis | jq -r '.items[] | select(.name=="stage-api") | .id')
          API_GATEWAY_URL="https://${API_ID}.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/prod"
      
          echo $USER_POOL_ID
          echo $CLIENT_ID
          echo $API_ID