name: Build React Native App with Expo

on:
  push:
    branches:
      - build-pipeline
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq make
          npm install -g expo-cli eas-cli
          cd clients/mobile
          npm install

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ap-south-1

      - name: Fetch Cognito and API Gateway Details
        run: |
          BRANCH_NAME=$(echo "${{ github.ref_name }}" | sed 's/[^a-zA-Z0-9]//g')
          echo "Branch Name: $BRANCH_NAME"

          # Fetch Cognito User Pool ID
          USER_POOL_ID=$(aws cognito-idp list-user-pools --max-results 20 | jq -r --arg name "${BRANCH_NAME}-user-pool" '.UserPools[] | select(.Name==$name) | .Id')

          # Fetch Cognito Client ID
          CLIENT_ID=$(aws cognito-idp list-user-pool-clients --user-pool-id $USER_POOL_ID --max-results 20 | jq -r --arg name "${BRANCH_NAME}-app-pool-client" '.UserPoolClients[] | select(.ClientName==$name) | .ClientId')

          # Fetch API Gateway ID
          API_ID=$(aws apigateway get-rest-apis | jq -r --arg name "${BRANCH_NAME}-api" '.items[] | select(.name==$name) | .id')
          API_GATEWAY_URL="https://${API_ID}.execute-api.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/api"

          echo "USER_POOL_ID=$USER_POOL_ID" >> $GITHUB_ENV
          echo "CLIENT_ID=$CLIENT_ID" >> $GITHUB_ENV
          echo "API_GATEWAY_URL=$API_GATEWAY_URL" >> $GITHUB_ENV

      - name: Create .env file
        run: |
          cd clients/mobile
          touch .env
          echo "API_URL=$API_GATEWAY_URL" >> .env
          echo "USER_POOL_ID=$USER_POOL_ID" >> .env
          echo "CLIENT_ID=$CLIENT_ID" >> .env
          echo "AWS_USER_POOL_ID=$USER_POOL_ID" >> .env
          echo "AWS_USER_POOL_CLIENT_ID=$CLIENT_ID" >> .env
          echo "AWS_COGNITO_DOMAIN=your_aws_cognito_domain" >> .env
          echo "EAS_PROJECT_ID=a0b97362-72f9-428f-a2da-d16445c6193b" >> .env
          echo "API_BASE_URL=$API_GATEWAY_URL" >> .env
          echo "APP_NAME=your_app_name" >> .env
          echo "APP_VERSION=your_app_version" >> .env
          echo "COUNTRY=your_country" >> .env

      - name: Set Up Environment
        run: cd clients/mobile && make setup-env
  
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: '9cC7lgYtP-ycBKfiDVE9Snmmu_mBL40bed9cwDaY'

      - name: Upload Environment Variables to Expo
        run: |
          cd clients/mobile
          make upload-env BUILD_PROFILE=production
        shell: bash
