name: "Continuous Deployment"

on:
  push:
    branches: [I-#17/CI-CD]
    tags:
      - "**"

permissions:
  contents: read

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref }}

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  TF_BACKEND_BUCKET_NAME: ${{ secrets.TF_BACKEND_BUCKET_NAME }}
  TF_BACKEND_BUCKET_KEY: ${{ secrets.TF_BACKEND_BUCKET_KEY }}
  TF_BACKEND_BUCKET_REGION: ${{ secrets.TF_BACKEND_BUCKET_REGION }}
  TF_VARS: >-
    -var="environment=${{ vars.ENVIRONMENT }}"
  RUNNER_IMAGE_NAME: github-runner-image

jobs:
  build-image:
    name: Build Deployment Image
    runs-on: ubuntu-22.04
    environment: production

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Build Runner Image
        run: make build-runner-image

  deploy-terraform:
    name: Deploy Terraform
    runs-on: ubuntu-22.04
    environment: production

    steps:
    - name: Run Terraform Validation
      run: make run-command-validate-terraform

    - name: Deploy
      run: make run-command-deploy
