# Guide: https://github.com/marketplace/actions/sphinx-to-github-pages
name: 📃 Docs Deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      - docs/**
      - openapi/**

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    name: Docs Publish
    runs-on: ${{ vars.RUNNER_OS }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Install Dot Binary
        run: sudo apt-get install -y graphviz

      - name: Install Redoc
        run: npm install -g @redocly/cli@latest

      - name: Combine OpenAPI specs
        run: redocly bundle openapi/versions/v1.json -o docs/openapi/v1.json --config openapi/configs/redocly.yaml

      - name: Deploy Docs
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          checkout: false
          documentation_path: "./docs"
          requirements_path: "./docs/requirements.txt"
