# Guide: https://github.com/marketplace/actions/sphinx-to-github-pages
name: Docs Deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      - docs/**

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  pages:
    name: Docs Publish
    runs-on: ubuntu-20.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Install Dot Binary
        run: sudo apt-get install -y graphviz
      - name: Install Redoc
        run: npm install -g @redocly/cli@latest
      - name: Test LS
        run: ls -l /home/runner/work
      - name: Combine OpenAPI specs
        working-directory: openapi/v1
        run: redocly bundle api.yaml -o combined.yaml
      - name: Deploy Docs
        id: deployment
        uses: sphinx-notes/pages@v3
        with:
          documentation_path: "./docs"
          requirements_path: "./docs/requirements.txt"
