# Guide: https://github.com/marketplace/actions/sphinx-to-github-pages
name: Docs Deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      - docs/**

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  set-runner-image-name:
    name: Set Runner Image Name
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Set Runner Image
        id: set_runner_image
        run: echo "runner_image_name=ghcr.io/craftsmenltd/bloodconnect-ci-image:$(md5sum ./Dockerfile | awk '{ print $1 }')" >> $GITHUB_OUTPUT
    outputs:
      runner_image_name: ${{ steps.set_runner_image.outputs.runner_image_name }}

  handle-docker-image:
    name: Handle Docker Image
    needs: set-runner-image-name
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit
    with:
      runner_image_name: ${{ needs.set-runner-image-name.outputs.runner_image_name }}

  pages:
    name: Docs
    needs: [set-runner-image-name, handle-docker-image]
    runs-on: ubuntu-20.04
    container:
      image: ${{ needs.set-runner-image-name.outputs.runner_image_name }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    environment:
      name: docs
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Deploy Docs
      id: deployment
      uses: sphinx-notes/pages@v3
