# Guide: https://github.com/marketplace/actions/sphinx-to-github-pages
name: Docs Deployment

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
    paths:
      - docs/**

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false


jobs:
  pages:
    name: Docs
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    - name: Install Dot Binary
      run: sudo apt-get install -y graphviz
    - name: Deploy Docs
      id: deployment
      uses: sphinx-notes/pages@v3
