name: "Branch Destruction"

on:
  workflow_dispatch:

jobs:
  set-destruction-environment:
    name: Set Destruction Environment
    runs-on: ubuntu-22.04
    outputs:
      deployment_environment: ${{ steps.set_destruction_env.outputs.deployment_environment }}
    steps:
      - name: Set Deployment Environment
        id: set_destruction_env
        run: echo "deployment_environment=$(echo "${{ github.ref }}" | sed -E 's#refs/heads/(.*)#\1#' | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

  branch-destruction:
    name: Branch Destruction
    needs: set-destruction-environment
    secrets: inherit
    uses: ./.github/workflows/aws-terraform.yml
    with:
      deployment_environment: ${{ needs.set-destruction-environment.outputs.deployment_environment }}
      github_environment: dev
      tf_backend_bucket_name: terraform-bloodconnect-ci-dev
      tf_backend_bucket_key: dev/${{ needs.set-destruction-environment.outputs.deployment_environment }}.tfstate
      tf_backend_bucket_region: ap-south-1
      aws_region: ap-south-1
      tf_action: destroy
      tf_vars: |
        TF_VAR_aws_environment=${{ needs.set-destruction-environment.outputs.deployment_environment }}
