name: "Branch Destruction"

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}

permissions:
  contents: read
  packages: write
  id-token: write
  
jobs:
  setup-environment:
    name: Set Deployment Environment
    runs-on: ${{ vars.RUNNER_OS }}
    environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Deployment Environment
        id: set_deployment_env
        run: echo "DEPLOYMENT_ENVIRONMENT=$(echo "${{ github.ref }}" | sed -E 's#refs/heads/(.*)#\1#' | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT

      - name: Fetch Deployment Metadata
        id: fetch_branch_metadata
        uses: ./.github/actions/fetch-deployment-metadata
        with:
          environment_name: ${{ steps.set_deployment_env.outputs.deployment_environment }}
          role_arn: ${{ secrets.AWS_ROLE_ARN }}
          aws_region: ${{ secrets.AWS_DEFAULT_REGION }}
          bucket_name: ${{ vars.TERRAFORM_BACKEND_BUCKET_NAME }}
    outputs:
      deployment_environment: ${{ steps.set_deployment_env.outputs.deployment_environment }}
      last_deployed_commit: ${{ steps.fetch_branch_metadata.outputs.last_deployed_commit }}

  handle-docker-image:
    name: Handle Docker Image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  destroy-branch:
    name: Destroy Branch
    secrets: inherit
    needs: [setup-environment, handle-docker-image]
    uses: ./.github/workflows/aws-terraform.yml
    with:
      docker_image: ${{ needs.handle-docker-image.outputs.runner_image_name }}
      github_environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
      deployment_environment: ${{ needs.setup-environment.outputs.deployment_environment }}
      last_deployed_commit: ${{ needs.setup-environment.outputs.last_deployed_commit }}
      aws_region: ap-south-1
      tf_action: destroy
