name: Docker Image Handling

on:
  workflow_call:
    inputs:
      runner_image_name:
        description: 'Docker image name'
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read
  packages: write

jobs:
  docker-image:
    name: Check Docker Image
    runs-on: ubuntu-22.04
    env:
      RUNNER_IMAGE_NAME: ${{ inputs.runner_image_name }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attempt to Pull Docker Image
        id: pull_docker_image
        run: docker manifest inspect ${{ inputs.runner_image_name }}
        continue-on-error: true

      - name: Build Docker Image
        if: steps.pull_docker_image.outcome == 'failure'
        run: make build-runner-image

      - name: Push Docker Image
        if: steps.pull_docker_image.outcome == 'failure'
        run: docker push ${{ inputs.runner_image_name }}
