name: 📱 Mobile App Build & Release

on:
  push:
    branches:
      - I-221-mobile-app-pipeline

permissions:
  contents: read
  packages: write
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  setup-environment:
    name: 🌱 Set Deployment Environment
    runs-on: ${{ vars.RUNNER_OS }}
    environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
    steps:
      - name: Set Deployment Environment
        id: set_deployment_env
        run: echo "DEPLOYMENT_ENVIRONMENT=$(echo "${{ github.ref }}" | sed -E 's#refs/heads/(.*)#\1#' | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT
    outputs:
      deployment_environment: ${{ steps.set_deployment_env.outputs.deployment_environment }}

  build-push-docker-image:
    name: 🐳 Build and Push Docker Image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  build-app:
    name: Build App
    runs-on: ${{ vars.RUNNER_OS }}
    environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
    needs: [setup-environment, build-push-docker-image]
    env:
      RUNNER_IMAGE_NAME: ${{ needs.build-push-docker-image.outputs.runner_image_name }}
      DEPLOYMENT_ENVIRONMENT: ${{ needs.setup-environment.outputs.deployment_environment }}
      MOBILE_APP_VERSION: 0.0.1
      EAS_PROJECT_ID: ${{ secrets.EAS_PROJECT_ID }}
      EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
      LOCATION_SERVICE_EMAIL: ${{ secrets.LOCATION_SERVICE_EMAIL }}
    steps:
      - name: 📥 Checkout Branch
        uses: actions/checkout@v4

      - name: 🔐 Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Install Node Modules
        run: make run-command-install-node-packages

      - name: 🔑 Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Generate env file
        run: make run-command-generate-env-file

      - name: Build App
        run: make run-command-build-mobile
