name: 📱 Mobile App Build & Release

on:
  push:
    branches:
      - I-221-mobile-app-pipeline

permissions:
  contents: read
  packages: write

defaults:
  run:
    shell: bash

jobs:
  setup-environment:
    name: 🌱 Set Deployment Environment
    runs-on: ${{ vars.RUNNER_OS }}
    environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
    steps:
      - name: Set Deployment Environment
        id: set_deployment_env
        run: echo "DEPLOYMENT_ENVIRONMENT=$(echo "${{ github.ref }}" | sed -E 's#refs/heads/(.*)#\1#' | awk '{print tolower($0)}')" >> $GITHUB_OUTPUT
    outputs:
      deployment_environment: ${{ steps.set_deployment_env.outputs.deployment_environment }}

  build-push-docker-image:
    name: 🐳 Build and Push Docker Image
    uses: ./.github/workflows/docker-image.yml
    secrets: inherit

  build-mobile-app:
    name: Build Mobile Application
    secrets:
      inherit
    needs: [ setup-environment, build-push-docker-image ]
    uses: ./.github/workflows/mobile-build.yml
    with:
      docker_image: ${{ needs.build-push-docker-image.outputs.runner_image_name }}
      github_environment: ${{ vars.ENVIRONMENT_GITHUB_DEV }}
      deployment_environment: ${{ needs.setup-environment.outputs.deployment_environment }}
      app_version: 0.0.1
      eas_project_id: ${{ secrets.EAS_PROJECT_ID }}
      expo_token: ${{ secrets.EXPO_TOKEN }}
      location_service_email: ${{ secrets.LOCATION_SERVICE_EMAIL }}
